////////////////////////////////////////////////////////////////////////////////
//
//    Copyright (c) 2014 - 2023.
//    Haixing Hu, Qubit Co. Ltd.
//
//    All rights reserved.
//
////////////////////////////////////////////////////////////////////////////////
import typeInfo from './type-info';
import isTypedArray from './is-typed-array';
import isString from './is-string';
import isNumeric from './is-numeric';
import isBoolean from './is-boolean';
import isError from './is-error';
import isArguments from './is-arguments';
import isWeak from './is-weak';
import isCollection from './is-collection';
import isBuffer from './is-buffer';
import isBuiltInClass from './is-built-in-class';
import isIntl from './is-intl';
import isIterator from './is-iterator';
import {
  SYMBOL_EXISTS,
  SYMBOL_ITERATOR_EXISTS,
  SYMBOL_MATCH_ALL_EXISTS,
  SYMBOL_TO_STRING_TAG_EXISTS,
  BIGINT_EXISTS,
  REGEXP_EXISTS,
  ARRAY_ISARRAY_EXISTS,
  AGGREGATEERROR_EXISTS,
  INTERNALERROR_EXISTS,
  MAP_EXISTS,
  SET_EXISTS,
  WEAKMAP_EXISTS,
  WEAKSET_EXISTS,
  INT8ARRAY_EXISTS,
  UINT8ARRAY_EXISTS,
  UINT8CLAMPEDARRAY_EXISTS,
  INT16ARRAY_EXISTS,
  UINT16ARRAY_EXISTS,
  INT32ARRAY_EXISTS,
  UINT32ARRAY_EXISTS,
  BIGINT64ARRAY_EXISTS,
  BIGUINT64ARRAY_EXISTS,
  FLOAT32ARRAY_EXISTS,
  FLOAT64ARRAY_EXISTS,
  ARRAYBUFFER_EXISTS,
  SHAREDARRAYBUFFER_EXISTS,
  DATAVIEW_EXISTS,
  WEAKREF_EXISTS,
  PROMISE_EXISTS,
  MAP_ENTRIES_EXISTS,
  SET_ENTRIES_EXISTS,
  MAP_ITERATOR_EXISTS,
  SET_ITERATOR_EXISTS,
  ARRAY_ITERATOR_EXISTS,
  STRING_ITERATOR_EXISTS,
  REGEXP_ITERATOR_EXISTS,
  INTL_EXISTS,
  INTL_COLLATOR_EXISTS,
  INTL_DATETIMEFORMAT_EXISTS,
  INTL_DISPLAYNAMES_EXISTS,
  INTL_DURATIONFORMAT_EXISTS,
  INTL_LISTFORMAT_EXISTS,
  INTL_LOCALE_EXISTS,
  INTL_NUMBERFORMAT_EXISTS,
  INTL_PLURALRULES_EXISTS,
  INTL_RELATIVETIMEFORMAT_EXISTS,
  INTL_SEGMENTER_EXISTS,
  INTL_SEGMENTER_ITERATOR_EXISTS,
  FINALIZATIONREGISTRY_EXISTS,
  ATOMICS_EXISTS,
  REFLECT_EXISTS,
  PROXY_EXISTS,
} from './feature-detect';
import {
  ArrayBufferPrototype,
  ArrayIteratorPrototype,
  BigInt64ArrayPrototype,
  BigUint64ArrayPrototype,
  DataViewPrototype,
  Float32ArrayPrototype,
  Float64ArrayPrototype,
  Int16ArrayPrototype,
  Int32ArrayPrototype,
  Int8ArrayPrototype,
  IntlCollatorPrototype,
  IntlDateTimeFormatPrototype,
  IntlDisplayNamesPrototype,
  IntlDurationFormatPrototype,
  IntlListFormatPrototype,
  IntlLocalePrototype,
  IntlNumberFormatPrototype,
  IntlPluralRulesPrototype,
  IntlRelativeTimeFormatPrototype,
  IntlSegmenterPrototype,
  IntelSegmentIteratorPrototype,
  MapIteratorPrototype,
  MapPrototype,
  PromisePrototype,
  RegExpIteratorPrototype,
  RegExpPrototype,
  SetIteratorPrototype,
  SetPrototype,
  SharedArrayBufferPrototype,
  StringIteratorPrototype,
  SymbolPrototype,
  Uint16ArrayPrototype,
  Uint32ArrayPrototype,
  Uint8ArrayPrototype,
  Uint8ClampedArrayPrototype,
  WeakMapPrototype,
  WeakRefPrototype,
  WeakSetPrototype,
  AggregateErrorPrototype,
  InternalErrorPrototype,
  FinalizationRegistryPrototype,
} from './impl/builtin-prototype';

export {
  typeInfo,
  isTypedArray,
  isString,
  isNumeric,
  isBoolean,
  isError,
  isArguments,
  isWeak,
  isCollection,
  isBuffer,
  isBuiltInClass,
  isIntl,
  isIterator,
  SYMBOL_EXISTS,
  SYMBOL_ITERATOR_EXISTS,
  SYMBOL_MATCH_ALL_EXISTS,
  SYMBOL_TO_STRING_TAG_EXISTS,
  BIGINT_EXISTS,
  REGEXP_EXISTS,
  ARRAY_ISARRAY_EXISTS,
  AGGREGATEERROR_EXISTS,
  INTERNALERROR_EXISTS,
  MAP_EXISTS,
  SET_EXISTS,
  WEAKMAP_EXISTS,
  WEAKSET_EXISTS,
  INT8ARRAY_EXISTS,
  UINT8ARRAY_EXISTS,
  UINT8CLAMPEDARRAY_EXISTS,
  INT16ARRAY_EXISTS,
  UINT16ARRAY_EXISTS,
  INT32ARRAY_EXISTS,
  UINT32ARRAY_EXISTS,
  BIGINT64ARRAY_EXISTS,
  BIGUINT64ARRAY_EXISTS,
  FLOAT32ARRAY_EXISTS,
  FLOAT64ARRAY_EXISTS,
  ARRAYBUFFER_EXISTS,
  SHAREDARRAYBUFFER_EXISTS,
  DATAVIEW_EXISTS,
  WEAKREF_EXISTS,
  PROMISE_EXISTS,
  MAP_ENTRIES_EXISTS,
  SET_ENTRIES_EXISTS,
  MAP_ITERATOR_EXISTS,
  SET_ITERATOR_EXISTS,
  ARRAY_ITERATOR_EXISTS,
  STRING_ITERATOR_EXISTS,
  REGEXP_ITERATOR_EXISTS,
  INTL_EXISTS,
  INTL_COLLATOR_EXISTS,
  INTL_DATETIMEFORMAT_EXISTS,
  INTL_DISPLAYNAMES_EXISTS,
  INTL_DURATIONFORMAT_EXISTS,
  INTL_LISTFORMAT_EXISTS,
  INTL_LOCALE_EXISTS,
  INTL_NUMBERFORMAT_EXISTS,
  INTL_PLURALRULES_EXISTS,
  INTL_RELATIVETIMEFORMAT_EXISTS,
  INTL_SEGMENTER_EXISTS,
  INTL_SEGMENTER_ITERATOR_EXISTS,
  FINALIZATIONREGISTRY_EXISTS,
  ATOMICS_EXISTS,
  REFLECT_EXISTS,
  PROXY_EXISTS,
  ArrayBufferPrototype,
  ArrayIteratorPrototype,
  BigInt64ArrayPrototype,
  BigUint64ArrayPrototype,
  DataViewPrototype,
  Float32ArrayPrototype,
  Float64ArrayPrototype,
  Int16ArrayPrototype,
  Int32ArrayPrototype,
  Int8ArrayPrototype,
  IntlCollatorPrototype,
  IntlDateTimeFormatPrototype,
  IntlDisplayNamesPrototype,
  IntlDurationFormatPrototype,
  IntlListFormatPrototype,
  IntlLocalePrototype,
  IntlNumberFormatPrototype,
  IntlPluralRulesPrototype,
  IntlRelativeTimeFormatPrototype,
  IntlSegmenterPrototype,
  IntelSegmentIteratorPrototype,
  MapIteratorPrototype,
  MapPrototype,
  PromisePrototype,
  RegExpIteratorPrototype,
  RegExpPrototype,
  SetIteratorPrototype,
  SetPrototype,
  SharedArrayBufferPrototype,
  StringIteratorPrototype,
  SymbolPrototype,
  Uint16ArrayPrototype,
  Uint32ArrayPrototype,
  Uint8ArrayPrototype,
  Uint8ClampedArrayPrototype,
  WeakMapPrototype,
  WeakRefPrototype,
  WeakSetPrototype,
  AggregateErrorPrototype,
  InternalErrorPrototype,
  FinalizationRegistryPrototype,
};

export default typeInfo;
